name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create config.js
        run: |
          echo "Creating config.js with API keys..."
          cat > config.js << EOL
          window.OPENAI_API_KEY = "${{ secrets.OPENAI_API_KEY }}";
          window.ELEVENLABS_API_KEY = "${{ secrets.ELEVENLABS_API_KEY }}";
          console.log('Config loaded - API Keys present:', {
            openai: window.OPENAI_API_KEY?.length > 0,
            elevenlabs: window.ELEVENLABS_API_KEY?.length > 0
          });
          EOL
          echo "Config file created with length: $(wc -c < config.js)"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages